name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev

    - name: Build project
      run: make

    - name: Run blockchain demo
      run: ./blockchain

    - name: Build tests
      run: make test

    - name: Run tests
      run: ./test_blockchain
